export default {
  grid: 'grid',
  lines: 'lines',
  search: 'search',
  xmarkCircleFill: 'xmarkCircleFill',
  chevronRight: 'chevronRight',
  musicCrotchetNote: 'musicCrotchetNote',
  musicBeamNote: 'musicBeamNote',
  musicList: 'musicList',
  person: 'person',
  play: 'play',
  pause: 'pause',
  forward: 'forward',
  backward: 'backward',
  xmark: 'xmark',
  notAllowed: 'notAllowed',
};
